AWSTemplateFormatVersion: '2010-09-09'
Description: 'Service Account - Monitoring Resources (CloudWatch Alarms, Dashboard, SNS)'

# ==============================================================================
# Parameters
# ==============================================================================
Parameters:
  Environment:
    Type: String
    Description: Environment name
    AllowedValues:
      - dev
      - prod
    Default: dev

  ProjectName:
    Type: String
    Description: Project name
    Default: sample-app

  AlertEmail:
    Type: String
    Description: Email address for alert notifications
    Default: dev-team@example.com

  CriticalAlertEmail:
    Type: String
    Description: Email address for critical alert notifications
    Default: ops-team@example.com

# ==============================================================================
# Resources
# ==============================================================================
Resources:
  # ----------------------------------------------------------------------------
  # SNS Topics
  # ----------------------------------------------------------------------------
  CriticalAlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${ProjectName}-${Environment}-CriticalAlert
      DisplayName: Critical Alert Notification
      Subscription:
        - Endpoint: !Ref CriticalAlertEmail
          Protocol: email
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-CriticalAlert
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  AlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${ProjectName}-${Environment}-Alert
      DisplayName: Alert Notification
      Subscription:
        - Endpoint: !Ref AlertEmail
          Protocol: email
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-Alert
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  # ----------------------------------------------------------------------------
  # ECS Alarms
  # ----------------------------------------------------------------------------
  PublicWebCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${ProjectName}-${Environment}-PublicWeb-CPU-High
      AlarmDescription: Public Web Service CPU usage exceeds 80%
      MetricName: CPUUtilization
      Namespace: AWS/ECS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80.0
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ServiceName
          Value:
            Fn::ImportValue: !Sub ${ProjectName}-${Environment}-public-web-service-name
        - Name: ClusterName
          Value:
            Fn::ImportValue: !Sub ${ProjectName}-${Environment}-ecs-cluster-name
      ActionsEnabled: true
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  PublicWebMemoryAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${ProjectName}-${Environment}-PublicWeb-Memory-High
      AlarmDescription: Public Web Service memory usage exceeds 90%
      MetricName: MemoryUtilization
      Namespace: AWS/ECS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 90.0
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ServiceName
          Value:
            Fn::ImportValue: !Sub ${ProjectName}-${Environment}-public-web-service-name
        - Name: ClusterName
          Value:
            Fn::ImportValue: !Sub ${ProjectName}-${Environment}-ecs-cluster-name
      ActionsEnabled: true
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  AdminDashboardCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${ProjectName}-${Environment}-AdminDashboard-CPU-High
      AlarmDescription: Admin Dashboard CPU usage exceeds 80%
      MetricName: CPUUtilization
      Namespace: AWS/ECS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80.0
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ServiceName
          Value:
            Fn::ImportValue: !Sub ${ProjectName}-${Environment}-admin-dashboard-service-name
        - Name: ClusterName
          Value:
            Fn::ImportValue: !Sub ${ProjectName}-${Environment}-ecs-cluster-name
      ActionsEnabled: true
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  AdminDashboardMemoryAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${ProjectName}-${Environment}-AdminDashboard-Memory-High
      AlarmDescription: Admin Dashboard memory usage exceeds 90%
      MetricName: MemoryUtilization
      Namespace: AWS/ECS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 90.0
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ServiceName
          Value:
            Fn::ImportValue: !Sub ${ProjectName}-${Environment}-admin-dashboard-service-name
        - Name: ClusterName
          Value:
            Fn::ImportValue: !Sub ${ProjectName}-${Environment}-ecs-cluster-name
      ActionsEnabled: true
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  # ----------------------------------------------------------------------------
  # ALB Alarms
  # ----------------------------------------------------------------------------
  ALBResponseTimeAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${ProjectName}-${Environment}-ALB-ResponseTime-High
      AlarmDescription: ALB response time exceeds 3 seconds
      MetricName: TargetResponseTime
      Namespace: AWS/ApplicationELB
      Statistic: Average
      Period: 60
      EvaluationPeriods: 3
      Threshold: 3.0
      ComparisonOperator: GreaterThanThreshold
      ActionsEnabled: true
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  ALB5xxErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${ProjectName}-${Environment}-ALB-5xxError
      AlarmDescription: ALB 5xx errors occurring frequently
      MetricName: HTTPCode_Target_5XX_Count
      Namespace: AWS/ApplicationELB
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 2
      Threshold: 10.0
      ComparisonOperator: GreaterThanThreshold
      ActionsEnabled: true
      AlarmActions:
        - !Ref CriticalAlertTopic
      TreatMissingData: notBreaching

  ALB4xxErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${ProjectName}-${Environment}-ALB-4xxError
      AlarmDescription: ALB 4xx errors occurring frequently
      MetricName: HTTPCode_Target_4XX_Count
      Namespace: AWS/ApplicationELB
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 100.0
      ComparisonOperator: GreaterThanThreshold
      ActionsEnabled: true
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  # ----------------------------------------------------------------------------
  # RDS Alarms
  # ----------------------------------------------------------------------------
  RDSCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${ProjectName}-${Environment}-RDS-CPU-High
      AlarmDescription: RDS CPU usage exceeds 80%
      MetricName: CPUUtilization
      Namespace: AWS/RDS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80.0
      ComparisonOperator: GreaterThanThreshold
      ActionsEnabled: true
      AlarmActions:
        - !Ref CriticalAlertTopic
      TreatMissingData: notBreaching

  RDSMemoryAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${ProjectName}-${Environment}-RDS-Memory-Low
      AlarmDescription: RDS freeable memory is below 500MB
      MetricName: FreeableMemory
      Namespace: AWS/RDS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 524288000
      ComparisonOperator: LessThanThreshold
      ActionsEnabled: true
      AlarmActions:
        - !Ref CriticalAlertTopic
      TreatMissingData: notBreaching

  RDSStorageAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${ProjectName}-${Environment}-RDS-Storage-Low
      AlarmDescription: RDS free storage is below 5GB
      MetricName: FreeStorageSpace
      Namespace: AWS/RDS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5368709120
      ComparisonOperator: LessThanThreshold
      ActionsEnabled: true
      AlarmActions:
        - !Ref CriticalAlertTopic
      TreatMissingData: notBreaching

  RDSConnectionsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${ProjectName}-${Environment}-RDS-Connections-High
      AlarmDescription: RDS connection count exceeds 80
      MetricName: DatabaseConnections
      Namespace: AWS/RDS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80.0
      ComparisonOperator: GreaterThanThreshold
      ActionsEnabled: true
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  RDSReadLatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${ProjectName}-${Environment}-RDS-ReadLatency-High
      AlarmDescription: RDS read latency exceeds 100ms
      MetricName: ReadLatency
      Namespace: AWS/RDS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 0.1
      ComparisonOperator: GreaterThanThreshold
      ActionsEnabled: true
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  RDSWriteLatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${ProjectName}-${Environment}-RDS-WriteLatency-High
      AlarmDescription: RDS write latency exceeds 200ms
      MetricName: WriteLatency
      Namespace: AWS/RDS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 0.2
      ComparisonOperator: GreaterThanThreshold
      ActionsEnabled: true
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  # ----------------------------------------------------------------------------
  # CloudWatch Dashboard
  # ----------------------------------------------------------------------------
  MainDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub ${ProjectName}-${Environment}-MainDashboard
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "title": "ECS - CPU Utilization",
                "region": "${AWS::Region}",
                "metrics": [
                  ["AWS/ECS", "CPUUtilization", {"stat": "Average", "label": "Public Web"}],
                  ["...", {"stat": "Average", "label": "Admin Dashboard"}]
                ],
                "period": 300,
                "yAxis": {"left": {"min": 0, "max": 100}}
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "title": "ECS - Memory Utilization",
                "region": "${AWS::Region}",
                "metrics": [
                  ["AWS/ECS", "MemoryUtilization", {"stat": "Average", "label": "Public Web"}],
                  ["...", {"stat": "Average", "label": "Admin Dashboard"}]
                ],
                "period": 300,
                "yAxis": {"left": {"min": 0, "max": 100}}
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 6,
              "width": 12,
              "height": 6,
              "properties": {
                "title": "ALB - Request Count",
                "region": "${AWS::Region}",
                "metrics": [
                  ["AWS/ApplicationELB", "RequestCount", {"stat": "Sum"}]
                ],
                "period": 60
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 6,
              "width": 12,
              "height": 6,
              "properties": {
                "title": "ALB - Target Response Time",
                "region": "${AWS::Region}",
                "metrics": [
                  ["AWS/ApplicationELB", "TargetResponseTime", {"stat": "Average"}]
                ],
                "period": 60,
                "yAxis": {"left": {"min": 0}}
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 12,
              "width": 12,
              "height": 6,
              "properties": {
                "title": "ALB - HTTP Status Codes",
                "region": "${AWS::Region}",
                "metrics": [
                  ["AWS/ApplicationELB", "HTTPCode_Target_2XX_Count", {"stat": "Sum", "label": "2xx"}],
                  ["...", "HTTPCode_Target_4XX_Count", {"stat": "Sum", "label": "4xx"}],
                  ["...", "HTTPCode_Target_5XX_Count", {"stat": "Sum", "label": "5xx"}]
                ],
                "period": 60
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 12,
              "width": 12,
              "height": 6,
              "properties": {
                "title": "RDS - CPU Utilization",
                "region": "${AWS::Region}",
                "metrics": [
                  ["AWS/RDS", "CPUUtilization", {"stat": "Average"}]
                ],
                "period": 300,
                "yAxis": {"left": {"min": 0, "max": 100}}
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 18,
              "width": 12,
              "height": 6,
              "properties": {
                "title": "RDS - Database Connections",
                "region": "${AWS::Region}",
                "metrics": [
                  ["AWS/RDS", "DatabaseConnections", {"stat": "Average"}]
                ],
                "period": 300,
                "yAxis": {"left": {"min": 0}}
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 18,
              "width": 12,
              "height": 6,
              "properties": {
                "title": "RDS - Read/Write Latency",
                "region": "${AWS::Region}",
                "metrics": [
                  ["AWS/RDS", "ReadLatency", {"stat": "Average", "label": "Read"}],
                  ["...", "WriteLatency", {"stat": "Average", "label": "Write"}]
                ],
                "period": 300,
                "yAxis": {"left": {"min": 0}}
              }
            }
          ]
        }

  # ----------------------------------------------------------------------------
  # Metric Filters (for Application Logs)
  # ----------------------------------------------------------------------------
  AppErrorMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      FilterPattern: '[timestamp, request_id, level = "ERROR", ...]'
      LogGroupName: /ecs/sample-app/public-web
      MetricTransformations:
        - MetricName: ApplicationErrorCount
          MetricNamespace: SampleApp/Logs
          MetricValue: '1'
          DefaultValue: 0

  AppErrorLogAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${ProjectName}-${Environment}-AppError-High
      AlarmDescription: Application error logs occurring frequently
      MetricName: ApplicationErrorCount
      Namespace: SampleApp/Logs
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 10.0
      ComparisonOperator: GreaterThanThreshold
      ActionsEnabled: true
      AlarmActions:
        - !Ref CriticalAlertTopic
      TreatMissingData: notBreaching

  # ----------------------------------------------------------------------------
  # Cost Budget
  # ----------------------------------------------------------------------------
  MonthlyCostBudget:
    Type: AWS::Budgets::Budget
    Properties:
      Budget:
        BudgetName: !Sub ${ProjectName}-${Environment}-MonthlyCost
        BudgetLimit:
          Amount: 100.0
          Unit: USD
        TimeUnit: MONTHLY
        BudgetType: COST
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 80.0
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref AlertEmail
        - Notification:
            NotificationType: FORECASTED
            ComparisonOperator: GREATER_THAN
            Threshold: 100.0
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref AlertEmail

# ==============================================================================
# Outputs
# ==============================================================================
Outputs:
  CriticalAlertTopicArn:
    Description: Critical Alert SNS Topic ARN
    Value: !Ref CriticalAlertTopic
    Export:
      Name: !Sub ${ProjectName}-${Environment}-critical-alert-topic-arn

  AlertTopicArn:
    Description: Alert SNS Topic ARN
    Value: !Ref AlertTopic
    Export:
      Name: !Sub ${ProjectName}-${Environment}-alert-topic-arn

  DashboardURL:
    Description: CloudWatch Dashboard URL
    Value: !Sub https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=${MainDashboard}
