AWSTemplateFormatVersion: '2010-09-09'
Description: 'Service Account - Database Stack (RDS PostgreSQL)'

# ===========================================================================
# Parameters
# ===========================================================================
Parameters:
  ProjectName:
    Type: String
    Default: sample-app
    Description: Project name for resource naming

  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment name

  VpcId:
    Type: String
    Description: Service VPC ID

  DatabaseSubnet1Id:
    Type: String
    Description: Database Subnet 1 ID

  DatabaseSubnet2Id:
    Type: String
    Description: Database Subnet 2 ID

  DBInstanceClass:
    Type: String
    Default: db.t3.medium
    AllowedValues:
      - db.t3.micro
      - db.t3.small
      - db.t3.medium
      - db.r6g.large
      - db.r6g.xlarge
    Description: RDS instance class

  DBAllocatedStorage:
    Type: Number
    Default: 100
    MinValue: 20
    MaxValue: 1000
    Description: Allocated storage in GB

  DBMasterUsername:
    Type: String
    Default: postgres
    Description: Master username for RDS

  DBName:
    Type: String
    Default: sampleappdb
    Description: Database name

  DBBackupRetentionPeriod:
    Type: Number
    Default: 7
    MinValue: 0
    MaxValue: 35
    Description: Backup retention period in days

# ===========================================================================
# Resources
# ===========================================================================
Resources:
  # -------------------------------------------------------------------------
  # DB Subnet Group
  # -------------------------------------------------------------------------
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Sub ${ProjectName}-${Environment}-db-subnet-group
      DBSubnetGroupDescription: Subnet group for RDS PostgreSQL
      SubnetIds:
        - !Ref DatabaseSubnet1Id
        - !Ref DatabaseSubnet2Id
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-db-subnet-group
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  # -------------------------------------------------------------------------
  # Security Group for RDS
  # -------------------------------------------------------------------------
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${ProjectName}-${Environment}-rds-sg
      GroupDescription: Security Group for RDS PostgreSQL
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        # Allow PostgreSQL from Private Subnets (ECS Tasks)
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 10.1.11.0/24
          Description: Allow PostgreSQL from Private Subnet 1a
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 10.1.12.0/24
          Description: Allow PostgreSQL from Private Subnet 1c
        # Allow PostgreSQL from Platform VPC (VPN access for admin)
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 10.0.0.0/16
          Description: Allow PostgreSQL from Platform VPC (VPN)
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-rds-sg
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  # -------------------------------------------------------------------------
  # Secrets Manager - DB Master Password
  # -------------------------------------------------------------------------
  DBMasterPassword:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${ProjectName}/${Environment}/db-master-password
      Description: RDS Master Password
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username": "${DBMasterUsername}"}'
        GenerateStringKey: password
        PasswordLength: 32
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-db-master-password
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  # -------------------------------------------------------------------------
  # RDS Parameter Group
  # -------------------------------------------------------------------------
  DBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      DBParameterGroupName: !Sub ${ProjectName}-${Environment}-postgres15-params
      Description: Custom parameter group for PostgreSQL 15
      Family: postgres15
      Parameters:
        max_connections: '200'
        shared_buffers: '{DBInstanceClassMemory/32768}'
        effective_cache_size: '{DBInstanceClassMemory/16384}'
        work_mem: '16384'
        maintenance_work_mem: '524288'
        log_min_duration_statement: '1000'
        log_connections: '1'
        log_disconnections: '1'
        log_duration: '0'
        log_statement: 'ddl'
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-postgres15-params
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  # -------------------------------------------------------------------------
  # RDS Instance (Multi-AZ)
  # -------------------------------------------------------------------------
  DBInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot
    Properties:
      DBInstanceIdentifier: !Sub ${ProjectName}-${Environment}-postgres
      DBName: !Ref DBName
      Engine: postgres
      EngineVersion: '15.4'
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref DBAllocatedStorage
      StorageType: gp3
      StorageEncrypted: true
      Iops: 3000
      MasterUsername: !Ref DBMasterUsername
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${DBMasterPassword}:SecretString:password}}'
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !Ref DBSecurityGroup
      DBParameterGroupName: !Ref DBParameterGroup
      MultiAZ: true
      PubliclyAccessible: false
      BackupRetentionPeriod: !Ref DBBackupRetentionPeriod
      PreferredBackupWindow: '18:00-19:00'
      PreferredMaintenanceWindow: 'sun:19:00-sun:20:00'
      EnableCloudwatchLogsExports:
        - postgresql
        - upgrade
      AutoMinorVersionUpgrade: true
      DeletionProtection: false
      CopyTagsToSnapshot: true
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-postgres
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  # -------------------------------------------------------------------------
  # Secrets Manager - DB Connection String
  # -------------------------------------------------------------------------
  DBConnectionString:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${ProjectName}/${Environment}/db-connection
      Description: RDS Connection Information
      SecretString: !Sub |
        {
          "host": "${DBInstance.Endpoint.Address}",
          "port": "${DBInstance.Endpoint.Port}",
          "database": "${DBName}",
          "username": "${DBMasterUsername}",
          "password": "{{resolve:secretsmanager:${DBMasterPassword}:SecretString:password}}"
        }
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-db-connection
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  # -------------------------------------------------------------------------
  # Secret Rotation (Optional - for production)
  # -------------------------------------------------------------------------
  # SecretRotationSchedule:
  #   Type: AWS::SecretsManager::RotationSchedule
  #   Properties:
  #     SecretId: !Ref DBMasterPassword
  #     RotationLambdaARN: !GetAtt RotationLambda.Arn
  #     RotationRules:
  #       AutomaticallyAfterDays: 30

# ===========================================================================
# Outputs
# ===========================================================================
Outputs:
  DBInstanceId:
    Description: RDS Instance ID
    Value: !Ref DBInstance
    Export:
      Name: !Sub ${ProjectName}-${Environment}-db-instance-id

  DBEndpointAddress:
    Description: RDS Endpoint Address
    Value: !GetAtt DBInstance.Endpoint.Address
    Export:
      Name: !Sub ${ProjectName}-${Environment}-db-endpoint-address

  DBEndpointPort:
    Description: RDS Endpoint Port
    Value: !GetAtt DBInstance.Endpoint.Port
    Export:
      Name: !Sub ${ProjectName}-${Environment}-db-endpoint-port

  DBName:
    Description: Database Name
    Value: !Ref DBName
    Export:
      Name: !Sub ${ProjectName}-${Environment}-db-name

  DBSecurityGroupId:
    Description: RDS Security Group ID
    Value: !Ref DBSecurityGroup
    Export:
      Name: !Sub ${ProjectName}-${Environment}-rds-sg-id

  DBMasterPasswordSecretArn:
    Description: DB Master Password Secret ARN
    Value: !Ref DBMasterPassword
    Export:
      Name: !Sub ${ProjectName}-${Environment}-db-master-password-arn

  DBConnectionStringSecretArn:
    Description: DB Connection String Secret ARN
    Value: !Ref DBConnectionString
    Export:
      Name: !Sub ${ProjectName}-${Environment}-db-connection-arn
