# ==============================================================================
# Service Account - 01 Network Stack
# ==============================================================================
# 目的: Service Account VPCとTransit Gateway接続を構築
# 構成: VPC, Subnets (Public x2, Private x2, Database x2), Transit Gateway Attachment
# 設計: Multi-AZ構成、Transit Gateway経由でPlatform VPCと接続
# デプロイ順序: 1番目
# ==============================================================================

AWSTemplateFormatVersion: '2010-09-09'
Description: 'Service Account Network Stack - VPC with Transit Gateway connectivity'

# ==============================================================================
# Parameters
# ==============================================================================
Parameters:
  ProjectName:
    Type: String
    Default: myapp
    Description: Project name for resource naming
    AllowedPattern: ^[a-z][a-z0-9-]*$

  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment name (dev or prod)

  VpcCidr:
    Type: String
    Default: 10.1.0.0/16
    Description: CIDR block for Service VPC
    AllowedPattern: ^(10\.\d{1,3}\.\d{1,3}\.\d{1,3}/16)$

  PlatformVpcCidr:
    Type: String
    Default: 10.0.0.0/16
    Description: CIDR block for Platform VPC (for routing)

  TransitGatewayId:
    Type: String
    Description: Transit Gateway ID (shared from Platform Account via RAM)
    AllowedPattern: ^tgw-[a-f0-9]{17}$

  TransitGatewayRouteTableId:
    Type: String
    Description: Transit Gateway Route Table ID (from Platform Account)
    AllowedPattern: ^tgw-rtb-[a-f0-9]{17}$

# ==============================================================================
# Metadata
# ==============================================================================
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Project Configuration"
        Parameters:
          - ProjectName
          - Environment
      - Label:
          default: "Network Configuration"
        Parameters:
          - VpcCidr
          - PlatformVpcCidr
      - Label:
          default: "Transit Gateway Configuration"
        Parameters:
          - TransitGatewayId
          - TransitGatewayRouteTableId

# ==============================================================================
# Resources
# ==============================================================================
Resources:
  # ----------------------------------------------------------------------------
  # VPC
  # ----------------------------------------------------------------------------
  ServiceVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-service-vpc
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: Service Account Application VPC

  # ----------------------------------------------------------------------------
  # Internet Gateway
  # 設計: Public Subnetのインターネット接続用
  # ----------------------------------------------------------------------------
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-service-igw
        - Key: Environment
          Value: !Ref Environment

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref ServiceVPC
      InternetGatewayId: !Ref InternetGateway

  # ----------------------------------------------------------------------------
  # Subnets - Public (Multi-AZ)
  # 設計: ALB配置用、NAT Gateway配置用
  # ----------------------------------------------------------------------------
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ServiceVPC
      CidrBlock: !Select [0, !Cidr [!Ref VpcCidr, 6, 8]]  # 10.1.0.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-service-public-subnet-1
        - Key: Environment
          Value: !Ref Environment
        - Key: Tier
          Value: Public

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ServiceVPC
      CidrBlock: !Select [1, !Cidr [!Ref VpcCidr, 6, 8]]  # 10.1.1.0/24
      AvailabilityZone: !Select [1, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-service-public-subnet-2
        - Key: Environment
          Value: !Ref Environment
        - Key: Tier
          Value: Public

  # ----------------------------------------------------------------------------
  # Subnets - Private (Multi-AZ)
  # 設計: ECS Fargate タスク配置用
  # ----------------------------------------------------------------------------
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ServiceVPC
      CidrBlock: !Select [2, !Cidr [!Ref VpcCidr, 6, 8]]  # 10.1.2.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-service-private-subnet-1
        - Key: Environment
          Value: !Ref Environment
        - Key: Tier
          Value: Private

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ServiceVPC
      CidrBlock: !Select [3, !Cidr [!Ref VpcCidr, 6, 8]]  # 10.1.3.0/24
      AvailabilityZone: !Select [1, !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-service-private-subnet-2
        - Key: Environment
          Value: !Ref Environment
        - Key: Tier
          Value: Private

  # ----------------------------------------------------------------------------
  # Subnets - Database (Multi-AZ)
  # 設計: RDS PostgreSQL配置用（独立サブネット）
  # ----------------------------------------------------------------------------
  DatabaseSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ServiceVPC
      CidrBlock: !Select [4, !Cidr [!Ref VpcCidr, 6, 8]]  # 10.1.4.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-service-database-subnet-1
        - Key: Environment
          Value: !Ref Environment
        - Key: Tier
          Value: Database

  DatabaseSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ServiceVPC
      CidrBlock: !Select [5, !Cidr [!Ref VpcCidr, 6, 8]]  # 10.1.5.0/24
      AvailabilityZone: !Select [1, !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-service-database-subnet-2
        - Key: Environment
          Value: !Ref Environment
        - Key: Tier
          Value: Database

  # ----------------------------------------------------------------------------
  # NAT Gateways (Multi-AZ)
  # 設計: Private Subnetからインターネットへの接続用
  # ----------------------------------------------------------------------------
  NatGateway1EIP:
    Type: AWS::EC2::EIP
    DependsOn: AttachGateway
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-service-nat-eip-1
        - Key: Environment
          Value: !Ref Environment

  NatGateway1:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGateway1EIP.AllocationId
      SubnetId: !Ref PublicSubnet1
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-service-nat-1
        - Key: Environment
          Value: !Ref Environment

  NatGateway2EIP:
    Type: AWS::EC2::EIP
    DependsOn: AttachGateway
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-service-nat-eip-2
        - Key: Environment
          Value: !Ref Environment

  NatGateway2:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGateway2EIP.AllocationId
      SubnetId: !Ref PublicSubnet2
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-service-nat-2
        - Key: Environment
          Value: !Ref Environment

  # ----------------------------------------------------------------------------
  # Transit Gateway Attachment
  # 設計: Service VPCをTransit Gatewayに接続
  # ----------------------------------------------------------------------------
  ServiceVpcTransitGatewayAttachment:
    Type: AWS::EC2::TransitGatewayAttachment
    Properties:
      TransitGatewayId: !Ref TransitGatewayId
      VpcId: !Ref ServiceVPC
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-service-tgw-attachment
        - Key: Environment
          Value: !Ref Environment

  # Transit Gateway Route Table Association
  ServiceVpcTransitGatewayRouteTableAssociation:
    Type: AWS::EC2::TransitGatewayRouteTableAssociation
    Properties:
      TransitGatewayAttachmentId: !Ref ServiceVpcTransitGatewayAttachment
      TransitGatewayRouteTableId: !Ref TransitGatewayRouteTableId

  # Transit Gateway Route Table Propagation
  ServiceVpcTransitGatewayRouteTablePropagation:
    Type: AWS::EC2::TransitGatewayRouteTablePropagation
    Properties:
      TransitGatewayAttachmentId: !Ref ServiceVpcTransitGatewayAttachment
      TransitGatewayRouteTableId: !Ref TransitGatewayRouteTableId

  # ----------------------------------------------------------------------------
  # Route Tables - Public
  # ----------------------------------------------------------------------------
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref ServiceVPC
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-service-public-rtb
        - Key: Environment
          Value: !Ref Environment

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  # ----------------------------------------------------------------------------
  # Route Tables - Private (各AZ独立)
  # 設計: NAT Gateway経由でインターネット、Transit Gateway経由でPlatform VPC
  # ----------------------------------------------------------------------------
  PrivateRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref ServiceVPC
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-service-private-rtb-1
        - Key: Environment
          Value: !Ref Environment

  # インターネット向けルート（NAT Gateway経由）
  PrivateRoute1:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable1
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway1

  # Platform VPC向けルート（Transit Gateway経由）
  PrivateRouteToPlatformVpc1:
    Type: AWS::EC2::Route
    DependsOn: ServiceVpcTransitGatewayAttachment
    Properties:
      RouteTableId: !Ref PrivateRouteTable1
      DestinationCidrBlock: !Ref PlatformVpcCidr
      TransitGatewayId: !Ref TransitGatewayId

  PrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet1
      RouteTableId: !Ref PrivateRouteTable1

  PrivateRouteTable2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref ServiceVPC
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-service-private-rtb-2
        - Key: Environment
          Value: !Ref Environment

  PrivateRoute2:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable2
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway2

  PrivateRouteToPlatformVpc2:
    Type: AWS::EC2::Route
    DependsOn: ServiceVpcTransitGatewayAttachment
    Properties:
      RouteTableId: !Ref PrivateRouteTable2
      DestinationCidrBlock: !Ref PlatformVpcCidr
      TransitGatewayId: !Ref TransitGatewayId

  PrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet2
      RouteTableId: !Ref PrivateRouteTable2

  # ----------------------------------------------------------------------------
  # Route Tables - Database
  # 設計: インターネット接続不要、Transit Gateway経由でPlatform VPCのみ
  # ----------------------------------------------------------------------------
  DatabaseRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref ServiceVPC
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-service-database-rtb
        - Key: Environment
          Value: !Ref Environment

  # Platform VPC向けルート（Transit Gateway経由）
  DatabaseRouteToPlatformVpc:
    Type: AWS::EC2::Route
    DependsOn: ServiceVpcTransitGatewayAttachment
    Properties:
      RouteTableId: !Ref DatabaseRouteTable
      DestinationCidrBlock: !Ref PlatformVpcCidr
      TransitGatewayId: !Ref TransitGatewayId

  DatabaseSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref DatabaseSubnet1
      RouteTableId: !Ref DatabaseRouteTable

  DatabaseSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref DatabaseSubnet2
      RouteTableId: !Ref DatabaseRouteTable

# ==============================================================================
# Outputs
# ==============================================================================
Outputs:
  VpcId:
    Description: Service VPC ID
    Value: !Ref ServiceVPC
    Export:
      Name: !Sub ${ProjectName}-${Environment}-service-vpc-id

  VpcCidr:
    Description: Service VPC CIDR Block
    Value: !Ref VpcCidr
    Export:
      Name: !Sub ${ProjectName}-${Environment}-service-vpc-cidr

  PublicSubnet1Id:
    Description: Public Subnet 1 ID
    Value: !Ref PublicSubnet1
    Export:
      Name: !Sub ${ProjectName}-${Environment}-service-public-subnet-1-id

  PublicSubnet2Id:
    Description: Public Subnet 2 ID
    Value: !Ref PublicSubnet2
    Export:
      Name: !Sub ${ProjectName}-${Environment}-service-public-subnet-2-id

  PrivateSubnet1Id:
    Description: Private Subnet 1 ID
    Value: !Ref PrivateSubnet1
    Export:
      Name: !Sub ${ProjectName}-${Environment}-service-private-subnet-1-id

  PrivateSubnet2Id:
    Description: Private Subnet 2 ID
    Value: !Ref PrivateSubnet2
    Export:
      Name: !Sub ${ProjectName}-${Environment}-service-private-subnet-2-id

  DatabaseSubnet1Id:
    Description: Database Subnet 1 ID
    Value: !Ref DatabaseSubnet1
    Export:
      Name: !Sub ${ProjectName}-${Environment}-service-database-subnet-1-id

  DatabaseSubnet2Id:
    Description: Database Subnet 2 ID
    Value: !Ref DatabaseSubnet2
    Export:
      Name: !Sub ${ProjectName}-${Environment}-service-database-subnet-2-id

  ServiceVpcTransitGatewayAttachmentId:
    Description: Service VPC Transit Gateway Attachment ID
    Value: !Ref ServiceVpcTransitGatewayAttachment
    Export:
      Name: !Sub ${ProjectName}-${Environment}-service-tgw-attachment-id
