AWSTemplateFormatVersion: '2010-09-09'
Description: 'Service Account - Monitoring Stack (CloudWatch Alarms, Dashboard, SNS)'

# ===========================================================================
# Parameters
# ===========================================================================
Parameters:
  ProjectName:
    Type: String
    Default: sample-app
    Description: Project name for resource naming

  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment name

  ECSClusterName:
    Type: String
    Description: ECS Cluster Name

  PublicWebServiceName:
    Type: String
    Description: Public Web Service Name

  AdminServiceName:
    Type: String
    Description: Admin Service Name

  DBInstanceId:
    Type: String
    Description: RDS Instance ID

  ALBFullName:
    Type: String
    Description: ALB Full Name (for metrics)

  TargetGroupFullName:
    Type: String
    Description: Target Group Full Name (for metrics)

  AlertEmail:
    Type: String
    Default: ops-team@example.com
    Description: Email address for CloudWatch Alarms

# ===========================================================================
# Resources
# ===========================================================================
Resources:
  # -------------------------------------------------------------------------
  # SNS Topic for Alarms
  # -------------------------------------------------------------------------
  AlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${ProjectName}-${Environment}-alerts
      DisplayName: CloudWatch Alerts
      Subscription:
        - Endpoint: !Ref AlertEmail
          Protocol: email
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-alerts
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  # -------------------------------------------------------------------------
  # CloudWatch Alarms - ECS
  # -------------------------------------------------------------------------
  # Public Web CPU High
  PublicWebCPUHighAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${ProjectName}-${Environment}-public-web-cpu-high
      AlarmDescription: Public Web CPU utilization is too high
      MetricName: CPUUtilization
      Namespace: AWS/ECS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ClusterName
          Value: !Ref ECSClusterName
        - Name: ServiceName
          Value: !Ref PublicWebServiceName
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  # Public Web Memory High
  PublicWebMemoryHighAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${ProjectName}-${Environment}-public-web-memory-high
      AlarmDescription: Public Web memory utilization is too high
      MetricName: MemoryUtilization
      Namespace: AWS/ECS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ClusterName
          Value: !Ref ECSClusterName
        - Name: ServiceName
          Value: !Ref PublicWebServiceName
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  # Public Web Task Count Low
  PublicWebTaskCountLowAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${ProjectName}-${Environment}-public-web-task-count-low
      AlarmDescription: Public Web running task count is below desired
      MetricName: RunningTaskCount
      Namespace: ECS/ContainerInsights
      Statistic: Average
      Period: 60
      EvaluationPeriods: 2
      Threshold: 2
      ComparisonOperator: LessThanThreshold
      Dimensions:
        - Name: ClusterName
          Value: !Ref ECSClusterName
        - Name: ServiceName
          Value: !Ref PublicWebServiceName
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: breaching

  # Admin CPU High
  AdminCPUHighAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${ProjectName}-${Environment}-admin-cpu-high
      AlarmDescription: Admin CPU utilization is too high
      MetricName: CPUUtilization
      Namespace: AWS/ECS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ClusterName
          Value: !Ref ECSClusterName
        - Name: ServiceName
          Value: !Ref AdminServiceName
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  # -------------------------------------------------------------------------
  # CloudWatch Alarms - RDS
  # -------------------------------------------------------------------------
  # RDS CPU High
  RDSCPUHighAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${ProjectName}-${Environment}-rds-cpu-high
      AlarmDescription: RDS CPU utilization is too high
      MetricName: CPUUtilization
      Namespace: AWS/RDS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref DBInstanceId
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  # RDS Free Storage Low
  RDSFreeStorageLowAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${ProjectName}-${Environment}-rds-free-storage-low
      AlarmDescription: RDS free storage is too low
      MetricName: FreeStorageSpace
      Namespace: AWS/RDS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 10737418240
      ComparisonOperator: LessThanThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref DBInstanceId
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  # RDS Database Connections High
  RDSDatabaseConnectionsHighAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${ProjectName}-${Environment}-rds-connections-high
      AlarmDescription: RDS database connections are too high
      MetricName: DatabaseConnections
      Namespace: AWS/RDS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 160
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref DBInstanceId
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  # RDS Read Latency High
  RDSReadLatencyHighAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${ProjectName}-${Environment}-rds-read-latency-high
      AlarmDescription: RDS read latency is too high
      MetricName: ReadLatency
      Namespace: AWS/RDS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 0.1
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref DBInstanceId
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  # RDS Write Latency High
  RDSWriteLatencyHighAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${ProjectName}-${Environment}-rds-write-latency-high
      AlarmDescription: RDS write latency is too high
      MetricName: WriteLatency
      Namespace: AWS/RDS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 0.1
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref DBInstanceId
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  # -------------------------------------------------------------------------
  # CloudWatch Alarms - ALB
  # -------------------------------------------------------------------------
  # ALB 5xx Errors High
  ALB5xxErrorsHighAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${ProjectName}-${Environment}-alb-5xx-errors-high
      AlarmDescription: ALB 5xx errors are too high
      MetricName: HTTPCode_Target_5XX_Count
      Namespace: AWS/ApplicationELB
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: LoadBalancer
          Value: !Ref ALBFullName
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  # ALB Target Response Time High
  ALBResponseTimeHighAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${ProjectName}-${Environment}-alb-response-time-high
      AlarmDescription: ALB target response time is too high
      MetricName: TargetResponseTime
      Namespace: AWS/ApplicationELB
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 1
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: LoadBalancer
          Value: !Ref ALBFullName
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  # ALB Unhealthy Host Count
  ALBUnhealthyHostCountAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${ProjectName}-${Environment}-alb-unhealthy-host-count
      AlarmDescription: ALB has unhealthy targets
      MetricName: UnHealthyHostCount
      Namespace: AWS/ApplicationELB
      Statistic: Average
      Period: 60
      EvaluationPeriods: 2
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: TargetGroup
          Value: !Ref TargetGroupFullName
        - Name: LoadBalancer
          Value: !Ref ALBFullName
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  # -------------------------------------------------------------------------
  # CloudWatch Dashboard
  # -------------------------------------------------------------------------
  MonitoringDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub ${ProjectName}-${Environment}-dashboard
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["AWS/ECS", "CPUUtilization", {"stat": "Average", "label": "Public Web CPU"}],
                  [".", "MemoryUtilization", {"stat": "Average", "label": "Public Web Memory"}]
                ],
                "period": 300,
                "stat": "Average",
                "region": "${AWS::Region}",
                "title": "ECS - Public Web Metrics",
                "yAxis": {"left": {"min": 0, "max": 100}}
              }
            },
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["AWS/RDS", "CPUUtilization", {"stat": "Average", "label": "RDS CPU"}],
                  [".", "DatabaseConnections", {"stat": "Average", "label": "Connections", "yAxis": "right"}]
                ],
                "period": 300,
                "stat": "Average",
                "region": "${AWS::Region}",
                "title": "RDS Metrics",
                "yAxis": {"left": {"min": 0, "max": 100}}
              }
            },
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["AWS/ApplicationELB", "TargetResponseTime", {"stat": "Average", "label": "Response Time"}],
                  [".", "RequestCount", {"stat": "Sum", "label": "Requests", "yAxis": "right"}]
                ],
                "period": 300,
                "stat": "Average",
                "region": "${AWS::Region}",
                "title": "ALB Metrics"
              }
            },
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["AWS/ApplicationELB", "HTTPCode_Target_2XX_Count", {"stat": "Sum", "label": "2xx", "color": "#2ca02c"}],
                  [".", "HTTPCode_Target_4XX_Count", {"stat": "Sum", "label": "4xx", "color": "#ff7f0e"}],
                  [".", "HTTPCode_Target_5XX_Count", {"stat": "Sum", "label": "5xx", "color": "#d62728"}]
                ],
                "period": 300,
                "stat": "Sum",
                "region": "${AWS::Region}",
                "title": "ALB HTTP Response Codes"
              }
            },
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["AWS/RDS", "ReadLatency", {"stat": "Average", "label": "Read Latency"}],
                  [".", "WriteLatency", {"stat": "Average", "label": "Write Latency"}]
                ],
                "period": 300,
                "stat": "Average",
                "region": "${AWS::Region}",
                "title": "RDS Latency"
              }
            },
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["AWS/RDS", "FreeStorageSpace", {"stat": "Average", "label": "Free Storage"}]
                ],
                "period": 300,
                "stat": "Average",
                "region": "${AWS::Region}",
                "title": "RDS Storage"
              }
            },
            {
              "type": "log",
              "properties": {
                "query": "SOURCE '/ecs/${ProjectName}/${Environment}/public-web'\n| fields @timestamp, @message\n| sort @timestamp desc\n| limit 20",
                "region": "${AWS::Region}",
                "title": "Recent Public Web Logs"
              }
            },
            {
              "type": "log",
              "properties": {
                "query": "SOURCE '/ecs/${ProjectName}/${Environment}/public-web'\n| filter @message like /ERROR/\n| fields @timestamp, @message\n| sort @timestamp desc\n| limit 20",
                "region": "${AWS::Region}",
                "title": "Recent Errors"
              }
            }
          ]
        }

# ===========================================================================
# Outputs
# ===========================================================================
Outputs:
  AlertTopicArn:
    Description: SNS Topic ARN for Alerts
    Value: !Ref AlertTopic
    Export:
      Name: !Sub ${ProjectName}-${Environment}-alert-topic-arn

  DashboardURL:
    Description: CloudWatch Dashboard URL
    Value: !Sub https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=${ProjectName}-${Environment}-dashboard
