AWSTemplateFormatVersion: '2010-09-09'
Description: 'CareApp - Shared Network Main Stack (Parent)'

Parameters:
  Environment:
    Type: String
    Default: POC
    AllowedValues:
      - POC
      - Production
    Description: Environment name

  TemplatesBucketName:
    Type: String
    Description: S3 bucket name where nested templates are stored
    Default: careapp-cfn-templates

  SharedVPCCIDR:
    Type: String
    Default: 10.0.0.0/16
    Description: CIDR block for Shared VPC

  PublicSubnet1CIDR:
    Type: String
    Default: 10.0.1.0/24
    Description: CIDR block for Public Subnet 1 (AZ-a)

  ClientVPNServerCertificateArn:
    Type: String
    Description: ACM Certificate ARN for Client VPN Server
    Default: ''

  ClientVPNClientCertificateArn:
    Type: String
    Description: ACM Certificate ARN for Client VPN Client (Mutual Auth)
    Default: ''

  ClientVPNCIDR:
    Type: String
    Default: 10.100.0.0/22
    Description: CIDR block for Client VPN clients

  AppVPCCIDR:
    Type: String
    Default: 10.1.0.0/16
    Description: CIDR block for App VPC (for routing)

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Environment Configuration
        Parameters:
          - Environment
          - TemplatesBucketName
      - Label:
          default: Network Configuration
        Parameters:
          - SharedVPCCIDR
          - PublicSubnet1CIDR
          - AppVPCCIDR
          - ClientVPNCIDR
      - Label:
          default: Client VPN Configuration
        Parameters:
          - ClientVPNServerCertificateArn
          - ClientVPNClientCertificateArn

Resources:
  # ========================================
  # Network Stack (VPC, Subnets, IGW, Route Tables)
  # ========================================
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplatesBucketName}.s3.${AWS::Region}.amazonaws.com/shared/templates/network.yaml
      Parameters:
        Environment: !Ref Environment
        SharedVPCCIDR: !Ref SharedVPCCIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
      TimeoutInMinutes: 15
      Tags:
        - Key: Name
          Value: !Sub CareApp-${Environment}-Stack-SharedNetwork
        - Key: Project
          Value: CareApp
        - Key: Environment
          Value: !Ref Environment

  # ========================================
  # Connectivity Stack (Transit Gateway, Client VPN)
  # ========================================
  ConnectivityStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: NetworkStack
    Properties:
      TemplateURL: !Sub https://${TemplatesBucketName}.s3.${AWS::Region}.amazonaws.com/shared/templates/connectivity.yaml
      Parameters:
        Environment: !Ref Environment
        SharedVPCID: !GetAtt NetworkStack.Outputs.SharedVPCID
        SharedVPCCIDR: !Ref SharedVPCCIDR
        PublicSubnet1ID: !GetAtt NetworkStack.Outputs.PublicSubnet1ID
        PublicRouteTableID: !GetAtt NetworkStack.Outputs.PublicRouteTableID
        AppVPCCIDR: !Ref AppVPCCIDR
        ClientVPNServerCertificateArn: !Ref ClientVPNServerCertificateArn
        ClientVPNClientCertificateArn: !Ref ClientVPNClientCertificateArn
        ClientVPNCIDR: !Ref ClientVPNCIDR
      TimeoutInMinutes: 20
      Tags:
        - Key: Name
          Value: !Sub CareApp-${Environment}-Stack-SharedConnectivity
        - Key: Project
          Value: CareApp
        - Key: Environment
          Value: !Ref Environment

Outputs:
  # VPC
  SharedVPCID:
    Description: Shared VPC ID
    Value: !GetAtt NetworkStack.Outputs.SharedVPCID
    Export:
      Name: !Sub CareApp-${Environment}-SharedNetwork-VPCID

  SharedVPCCIDR:
    Description: Shared VPC CIDR
    Value: !Ref SharedVPCCIDR
    Export:
      Name: !Sub CareApp-${Environment}-SharedNetwork-VPCCIDR

  PublicSubnet1ID:
    Description: Public Subnet 1 ID
    Value: !GetAtt NetworkStack.Outputs.PublicSubnet1ID
    Export:
      Name: !Sub CareApp-${Environment}-SharedNetwork-PublicSubnet1ID

  # Transit Gateway
  TransitGatewayID:
    Description: Transit Gateway ID
    Value: !GetAtt ConnectivityStack.Outputs.TransitGatewayID
    Export:
      Name: !Sub CareApp-${Environment}-SharedNetwork-TransitGatewayID

  # Client VPN
  ClientVPNEndpointID:
    Description: Client VPN Endpoint ID
    Value: !GetAtt ConnectivityStack.Outputs.ClientVPNEndpointID
    Export:
      Name: !Sub CareApp-${Environment}-SharedNetwork-ClientVPNEndpointID
    Condition: HasClientVPN

  ClientVPNDNSName:
    Description: Client VPN DNS Name
    Value: !GetAtt ConnectivityStack.Outputs.ClientVPNDNSName
    Export:
      Name: !Sub CareApp-${Environment}-SharedNetwork-ClientVPNDNSName
    Condition: HasClientVPN

Conditions:
  HasClientVPN: !And
    - !Not [!Equals [!Ref ClientVPNServerCertificateArn, '']]
    - !Not [!Equals [!Ref ClientVPNClientCertificateArn, '']]