AWSTemplateFormatVersion: '2010-09-09'
Description: 'Platform Account - Network Stack (Nested)'

# ===========================================================================
# Parameters
# ===========================================================================
Parameters:
  ProjectName:
    Type: String
    Default: sample-app
    Description: Project name for resource naming

  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment name

  VpcCidr:
    Type: String
    Default: 10.0.0.0/16
    Description: Platform VPC CIDR

# ===========================================================================
# Resources
# ===========================================================================
Resources:
  # -------------------------------------------------------------------------
  # VPC
  # -------------------------------------------------------------------------
  PlatformVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-platform-vpc
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  # -------------------------------------------------------------------------
  # Internet Gateway
  # -------------------------------------------------------------------------
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-platform-igw
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref PlatformVPC
      InternetGatewayId: !Ref InternetGateway

  # -------------------------------------------------------------------------
  # Public Subnets
  # -------------------------------------------------------------------------
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref PlatformVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-platform-public-1a
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref PlatformVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [1, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-platform-public-1c
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  # -------------------------------------------------------------------------
  # Private Subnets
  # -------------------------------------------------------------------------
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref PlatformVPC
      CidrBlock: 10.0.11.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-platform-private-1a
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref PlatformVPC
      CidrBlock: 10.0.12.0/24
      AvailabilityZone: !Select [1, !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-platform-private-1c
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  # -------------------------------------------------------------------------
  # Transit Gateway Subnets
  # -------------------------------------------------------------------------
  TgwSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref PlatformVPC
      CidrBlock: 10.0.21.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-platform-tgw-1a
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  TgwSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref PlatformVPC
      CidrBlock: 10.0.22.0/24
      AvailabilityZone: !Select [1, !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-platform-tgw-1c
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  # -------------------------------------------------------------------------
  # NAT Gateways
  # -------------------------------------------------------------------------
  NatGateway1EIP:
    Type: AWS::EC2::EIP
    DependsOn: AttachGateway
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-platform-nat-eip-1a
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  NatGateway2EIP:
    Type: AWS::EC2::EIP
    DependsOn: AttachGateway
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-platform-nat-eip-1c
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  NatGateway1:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGateway1EIP.AllocationId
      SubnetId: !Ref PublicSubnet1
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-platform-nat-1a
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  NatGateway2:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGateway2EIP.AllocationId
      SubnetId: !Ref PublicSubnet2
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-platform-nat-1c
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  # -------------------------------------------------------------------------
  # Route Tables
  # -------------------------------------------------------------------------
  # Public Route Table
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref PlatformVPC
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-platform-public-rt
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  # Private Route Table 1 (AZ-1a)
  PrivateRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref PlatformVPC
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-platform-private-rt-1a
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  PrivateRoute1:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable1
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway1

  PrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet1
      RouteTableId: !Ref PrivateRouteTable1

  # Private Route Table 2 (AZ-1c)
  PrivateRouteTable2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref PlatformVPC
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-platform-private-rt-1c
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  PrivateRoute2:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable2
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway2

  PrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet2
      RouteTableId: !Ref PrivateRouteTable2

  # Transit Gateway Route Table 1 (AZ-1a)
  TgwRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref PlatformVPC
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-platform-tgw-rt-1a
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  TgwSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref TgwSubnet1
      RouteTableId: !Ref TgwRouteTable1

  # Transit Gateway Route Table 2 (AZ-1c)
  TgwRouteTable2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref PlatformVPC
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-platform-tgw-rt-1c
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  TgwSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref TgwSubnet2
      RouteTableId: !Ref TgwRouteTable2

# ===========================================================================
# Outputs
# ===========================================================================
Outputs:
  VpcId:
    Description: Platform VPC ID
    Value: !Ref PlatformVPC
    Export:
      Name: !Sub ${ProjectName}-${Environment}-platform-vpc-id

  VpcCidr:
    Description: Platform VPC CIDR
    Value: !Ref VpcCidr
    Export:
      Name: !Sub ${ProjectName}-${Environment}-platform-vpc-cidr

  PublicSubnet1Id:
    Description: Public Subnet 1 ID (AZ-1a)
    Value: !Ref PublicSubnet1
    Export:
      Name: !Sub ${ProjectName}-${Environment}-platform-public-subnet-1a

  PublicSubnet2Id:
    Description: Public Subnet 2 ID (AZ-1c)
    Value: !Ref PublicSubnet2
    Export:
      Name: !Sub ${ProjectName}-${Environment}-platform-public-subnet-1c

  PrivateSubnet1Id:
    Description: Private Subnet 1 ID (AZ-1a)
    Value: !Ref PrivateSubnet1
    Export:
      Name: !Sub ${ProjectName}-${Environment}-platform-private-subnet-1a

  PrivateSubnet2Id:
    Description: Private Subnet 2 ID (AZ-1c)
    Value: !Ref PrivateSubnet2
    Export:
      Name: !Sub ${ProjectName}-${Environment}-platform-private-subnet-1c

  TgwSubnet1Id:
    Description: Transit Gateway Subnet 1 ID (AZ-1a)
    Value: !Ref TgwSubnet1
    Export:
      Name: !Sub ${ProjectName}-${Environment}-platform-tgw-subnet-1a

  TgwSubnet2Id:
    Description: Transit Gateway Subnet 2 ID (AZ-1c)
    Value: !Ref TgwSubnet2
    Export:
      Name: !Sub ${ProjectName}-${Environment}-platform-tgw-subnet-1c

  PrivateRouteTable1Id:
    Description: Private Route Table 1 ID (AZ-1a)
    Value: !Ref PrivateRouteTable1

  PrivateRouteTable2Id:
    Description: Private Route Table 2 ID (AZ-1c)
    Value: !Ref PrivateRouteTable2

  TgwRouteTable1Id:
    Description: Transit Gateway Route Table 1 ID (AZ-1a)
    Value: !Ref TgwRouteTable1

  TgwRouteTable2Id:
    Description: Transit Gateway Route Table 2 ID (AZ-1c)
    Value: !Ref TgwRouteTable2
