AWSTemplateFormatVersion: '2010-09-09'
Description: 'Platform Account - Main Stack (Nested)'

# ===========================================================================
# Parameters
# ===========================================================================
Parameters:
  ProjectName:
    Type: String
    Default: sample-app
    Description: Project name for resource naming

  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment name

  ServiceAccountId:
    Type: String
    Description: Service Account AWS Account ID for RAM sharing

  VpcCidr:
    Type: String
    Default: 10.0.0.0/16
    Description: Platform VPC CIDR

  ClientVpnCidr:
    Type: String
    Default: 172.16.0.0/22
    Description: Client VPN CIDR

  ServerCertificateArn:
    Type: String
    Description: ACM Certificate ARN for VPN Server

  ClientRootCertificateArn:
    Type: String
    Description: ACM Certificate ARN for VPN Client

  NestedTemplatesBucketName:
    Type: String
    Description: S3 Bucket name for nested templates

# ===========================================================================
# Resources
# ===========================================================================
Resources:
  # Network Stack (Nested)
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${NestedTemplatesBucketName}.s3.ap-northeast-1.amazonaws.com/nested/network.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        VpcCidr: !Ref VpcCidr
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-network-stack
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  # Connectivity Stack (Nested)
  ConnectivityStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: NetworkStack
    Properties:
      TemplateURL: !Sub https://${NestedTemplatesBucketName}.s3.ap-northeast-1.amazonaws.com/nested/connectivity.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        TgwSubnet1Id: !GetAtt NetworkStack.Outputs.TgwSubnet1Id
        TgwSubnet2Id: !GetAtt NetworkStack.Outputs.TgwSubnet2Id
        PrivateSubnet1Id: !GetAtt NetworkStack.Outputs.PrivateSubnet1Id
        PrivateSubnet2Id: !GetAtt NetworkStack.Outputs.PrivateSubnet2Id
        ClientVpnCidr: !Ref ClientVpnCidr
        ServerCertificateArn: !Ref ServerCertificateArn
        ClientRootCertificateArn: !Ref ClientRootCertificateArn
        ServiceAccountId: !Ref ServiceAccountId
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-connectivity-stack
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

# ===========================================================================
# Outputs
# ===========================================================================
Outputs:
  VpcId:
    Description: Platform VPC ID
    Value: !GetAtt NetworkStack.Outputs.VpcId
    Export:
      Name: !Sub ${ProjectName}-${Environment}-platform-vpc-id

  VpcCidr:
    Description: Platform VPC CIDR
    Value: !Ref VpcCidr
    Export:
      Name: !Sub ${ProjectName}-${Environment}-platform-vpc-cidr

  TransitGatewayId:
    Description: Transit Gateway ID
    Value: !GetAtt ConnectivityStack.Outputs.TransitGatewayId
    Export:
      Name: !Sub ${ProjectName}-${Environment}-tgw-id

  ClientVpnEndpointId:
    Description: Client VPN Endpoint ID
    Value: !GetAtt ConnectivityStack.Outputs.ClientVpnEndpointId
    Export:
      Name: !Sub ${ProjectName}-${Environment}-vpn-endpoint-id
